language: php

php:
  - 5.6
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

install:
  - |
    if [ $(phpenv version-name) = "7.1" ]; then
    composer require php-coveralls/php-coveralls;
    composer require --dev phpstan/phpstan;
    fi

script:
  - mkdir -p build/logs
  - |
    if [ $(phpenv version-name) = "7.1" ]; then
    vendor/bin/phpstan analyse src --level 1 -c phpstan.neon;
    fi
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - |
    if [ $(phpenv version-name) = "7.1" ]; then
    travis_retry php vendor/bin/php-coveralls -v;
    fi