language: php

php:
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

install:
  - composer require satooshi/php-coveralls
  - |
    composer global require phpstan/phpstan dev-master --prefer-dist \
    && composer global show | grep phpstan

script:
  - mkdir -p build/logs
  - phpstan analyse src --level 1 -c phpstan.neon
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v


